language: generic 
sudo: required 
services:
  - docker
  
before_install:
  - docker build -t karmacode/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true karmacode/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "react-docker"
  env: "Reactdocker-env"
  bucket_name: "elasticbeanstalk-us-west-1-186881474644"
  bucket_path: "react-docker"
  skip_cleanup: true
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"

  
  
  
