language: generic 
sudo: required 
services:
  - docker
  
before_install:
  - docker build -t karmacode/docker-react -f Dockerfile.dev .
  
script:
  - docker run -e CI=true karmacode/docker-react npm run test

deploy: 
  provider: elesticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-186881474644"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  
  
  
